import { Round } from './round';

export const ROUNDS16: Round[] = [
    { 
      date: '15/02 - 21UTC',
      player1: 'SuperSquirrel51',
      country1: '../../assets/images/flag/ca.png',
      img1: '../../assets/images/playerspfp/SuperSquirrel51.jpg',
      player2: 'Champs de ble',
      country2: '../../assets/images/flag/fr.png',
      img2: '../../assets/images/playerspfp/Champs de ble.jpg',
      referee: 'travis_ba',
      streamer: 'E-M-i',
      commentators: ['QEpicAce', 'E-M-i'],
      mplink: 'https://osu.ppy.sh/community/matches/58476069',
    },
    { 
      date: '15/02 - 16UTC',
      player1: 'Katsumi',
      country1: '../../assets/images/flag/de.png',
      img1: '../../assets/images/playerspfp/Katsumi.png',
      player2: 'Megafan',
      country2: '../../assets/images/flag/ar.png',
      img2: '../../assets/images/playerspfp/Megafan.png',
      referee: 'E-M-i',
      streamer: 'ITotallyGetThat',
      commentators: ['E-M-i', 'Kasumii-Sama'],
      mplink: 'https://osu.ppy.sh/community/matches/58467487',
    },
    { 
      date: '15/02 - 15UTC',
      player1: 'Santeri',
      country1: '../../assets/images/flag/fi.png',
      img1: '../../assets/images/playerspfp/Santeri.png',
      player2: 'Kozzo',
      country2: '../../assets/images/flag/it.png',
      img2: '../../assets/images/playerspfp/Kozzo.jpg',
      referee: 'Sayira',
      streamer: 'Sayira',
      commentators: ['Finite', 'Kasumii-Sama'],
      mplink: 'https://osu.ppy.sh/community/matches/58465670',
    },
    { 
      date: '//',
      player1: 'zd101nb',
      country1: '../../assets/images/flag/cn.png',
      img1: '../../assets/images/playerspfp/zd101nb.jpg',
      player2: 'Kirross',
      country2: '../../assets/images/flag/de.png',
      img2: '../../assets/images/playerspfp/Kirross.jpg',
      referee: '//',
      streamer: '//',
      commentators: ['//'],
      mplink: '//',
    },
    { 
      date: '14/02 - 12UTC',
      player1: 'Arbusion',
      country1: '../../assets/images/flag/au.png',
      img1: '../../assets/images/playerspfp/Arbusion.jpg',
      player2: 'Blujae',
      country2: '../../assets/images/flag/nz.png',
      img2: '../../assets/images/playerspfp/Blujae.jpg',
      referee: 'Element118',
      streamer: 'Element118',
      commentators: ['NutAndGo', 'Sparxe'],
      mplink: 'https://osu.ppy.sh/mp/58433048',
    },
    { 
      date: '16/02 - 20UTC',
      player1: 'Yeong Yuseong',
      country1: '../../assets/images/flag/us.png',
      img1: '../../assets/images/playerspfp/Yeong Yuseong.jpg',
      player2: '-Storm7-',
      country2: '../../assets/images/flag/hk.png',
      img2: '../../assets/images/playerspfp/-Storm7-.jpg',
      referee: 'travis_ba',
      streamer: 'ITotallyGetThat',
      commentators: ['E-M-i'],
      mplink: 'https://osu.ppy.sh/community/matches/58504436',
    },
    { 
      date: '15/02 - 14UTC',
      player1: 'Samoyed',
      country1: '../../assets/images/flag/fi.png',
      img1: '../../assets/images/playerspfp/Samoyed.jpg',
      player2: 'Vasyadogs',
      country2: '../../assets/images/flag/ru.png',
      img2: '../../assets/images/playerspfp/Vasyadogs.jpg',
      referee: 'Starger',
      streamer: 'E-M-i',
      commentators: ['E-M-i'],
      mplink: 'https://osu.ppy.sh/community/matches/58464156',
    },
    { 
      date: '//',
      player1: 'Pickxarro',
      country1: '../../assets/images/flag/fi.png',
      img1: '../../assets/images/playerspfp/Pickxarro.jpg',
      player2: 'DrDazzle',
      country2: '../../assets/images/flag/by.png',
      img2: '../../assets/images/playerspfp/DrDazzle.png',
      referee: '//',
      streamer: '//',
      commentators: ['//'],
      mplink: '//',
    },
    { 
      date: '14/02 - 14UTC',
      player1: 'Malox',
      country1: '../../assets/images/flag/de.png',
      img1: '../../assets/images/playerspfp/Malox.png',
      player2: 'Maou',
      country2: '../../assets/images/flag/de.png',
      img2: '../../assets/images/playerspfp/Maou.jpg',
      referee: 'Sayira',
      streamer: 'Sayira',
      commentators: ['QEpicAce', 'Finite'],
      mplink: 'https://osu.ppy.sh/community/matches/58440442',
    },
    { 
      date: '15/02 - 14UTC',
      player1: 'awdse22',
      country1: '../../assets/images/flag/sg.png',
      img1: '../../assets/images/playerspfp/awdse22.png',
      player2: 'Dartandr',
      country2: '../../assets/images/flag/ru.png',
      img2: '../../assets/images/playerspfp/Dartandr.jpg',
      referee: 'Sayira',
      streamer: 'Sayira',
      commentators: ['QEpicAce'],
      mplink: 'https://osu.ppy.sh/mp/58464162',
    },
    { 
      date: '15/02 - 17UTC',
      player1: 'Vaf',
      country1: '../../assets/images/flag/ar.png',
      img1: '../../assets/images/playerspfp/Vaf.jpg',
      player2: 'Boaz',
      country2: '../../assets/images/flag/nl.png',
      img2: '../../assets/images/playerspfp/Boaz.png',
      referee: 'Ladylag	',
      streamer: 'E-M-i',
      commentators: ['Finite', 'QEpicAce'],
      mplink: 'https://osu.ppy.sh/community/matches/58469338',
    },
    { 
      date: '15/02 - 12UTC',
      player1: 'helios44',
      country1: '../../assets/images/flag/sg.png',
      img1: '../../assets/images/playerspfp/helios44.png',
      player2: 'Enohx',
      country2: '../../assets/images/flag/de.png',
      img2: '../../assets/images/playerspfp/Enohx.jpg',
      referee: 'Sayira',
      streamer: 'Sayira',
      commentators: ['Finite', 'QEpicAce'],
      mplink: 'https://osu.ppy.sh/community/matches/58461271',
    },
    { 
      date: '16/02 - 22UTC',
      player1: 'Loliezi1337',
      country1: '../../assets/images/flag/us.png',
      img1: '../../assets/images/playerspfp/Loliezi1337.jpg',
      player2: 'Olii',
      country2: '../../assets/images/flag/uk.jpg',
      img2: '../../assets/images/playerspfp/Olii.jpg',
      referee: 'travis_ba',
      streamer: 'ITotallyGetThat',
      commentators: ['ITotallyGetThat'],
      mplink: 'https://osu.ppy.sh/community/matches/58507300',
    },
    { 
      date: '16/02 - 15UTC',
      player1: 'BadAimBoi',
      country1: '../../assets/images/flag/pl.png',
      img1: '../../assets/images/playerspfp/BadAimBoi.jpg',
      player2: 'TLQ_Yoshii',
      country2: '../../assets/images/flag/fr.png',
      img2: '../../assets/images/playerspfp/TLQ_Yoshii.jpg',
      referee: 'Sayira',
      streamer: 'Sayira',
      commentators: ['QEpicAce'],
      mplink: 'https://osu.ppy.sh/community/matches/58496768',
    },
    { 
      date: '16/02 - 17UTC',
      player1: 'DrugManager',
      country1: '../../assets/images/flag/de.png',
      img1: '../../assets/images/playerspfp/DrugManager.png',
      player2: 'moosepi',
      country2: '../../assets/images/flag/sg.png',
      img2: '../../assets/images/playerspfp/moosepi.png',
      referee: 'Sayira',
      streamer: 'Sayira',
      commentators: ['Kasumii-Sama', 'QEpicAce'],
      mplink: 'https://osu.ppy.sh/community/matches/58499885',
    },
    { 
      date: '15/02 - 15UTC',
      player1: 'ByTiger',
      country1: '../../assets/images/flag/de.png',
      img1: '../../assets/images/playerspfp/ByTiger.jpg',
      player2: 'squidstain',
      country2: '../../assets/images/flag/my.png',
      img2: '../../assets/images/playerspfp/squidstain.jpg',
      referee: 'Sayira',
      streamer: 'E-M-i',
      commentators: ['QEpicAce'],
      mplink: 'https://osu.ppy.sh/community/matches/58465676',
    }
];