import { Round } from './round';

export const ROUNDS32: Round[] = [
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    },
    { 
      date: '15/02',
      player1: 'John Doe',
      country1: '../../assets/images/flag/france.png',
      img1: 'https://via.placeholder.com/50',
      player2: 'Marc Raiffe',
      country2: '../../assets/images/flag/canada.png',
      img2: 'https://via.placeholder.com/50',
      referee: 'LadyLag',
      streamer: 'Alphacast',
      commentators: ['LadyBug', 'TheCommentator'],
      twitch: 'twitch.com'
    }
];