import { Round } from './round';

export const ROUNDS32: Round[] = [
    { 
      date: '08/02 - 18UTC',
      player1: 'Malox',
      country1: '../../assets/images/flag/de.png',
      img1: '../../assets/images/playerspfp/Malox.png',
      player2: 'SuperSquirrel51',
      country2: '../../assets/images/flag/ca.png',
      img2: '../../assets/images/playerspfp/SuperSquirrel51.jpg',
      referee: 'E-M-i',
      streamer: 'ITotallyGetThat',
      commentators: ['Finite', 'E-M-i'],
      mplink: 'https://osu.ppy.sh/community/matches/58298366',
    },
    { 
      date: '//',
      player1: 'Maou',
      country1: '../../assets/images/flag/de.png',
      img1: '../../assets/images/playerspfp/Maou.jpg',
      player2: 'Champs de ble',
      country2: '../../assets/images/flag/fr.png',
      img2: '../../assets/images/playerspfp/Champs de ble.jpg',
      referee: '//',
      streamer: '//',
      commentators: ['//'],
      mplink: '//',
    },
    { 
      date: '08/02 - 14:30UTC',
      player1: 'awdse22',
      country1: '../../assets/images/flag/sg.png',
      img1: '../../assets/images/playerspfp/awdse22.png',
      player2: 'Katsumi',
      country2: '../../assets/images/flag/de.png',
      img2: '../../assets/images/playerspfp/Katsumi.png',
      referee: 'Satsukel',
      streamer: 'ITotallyGetThat',
      commentators: ['Maou', 'Malox'],
      mplink: 'https://osu.ppy.sh/community/matches/58292406',
    },
    { 
      date: '08/02 - 16UTC',
      player1: 'Megafan',
      country1: '../../assets/images/flag/ar.png',
      img1: '../../assets/images/playerspfp/Megafan.png',
      player2: 'Dartandr',
      country2: '../../assets/images/flag/ru.png',
      img2: '../../assets/images/playerspfp/Dartandr.jpg',
      referee: 'Starger',
      streamer: 'ITotallyGetThat',
      commentators: ['Finite', 'Heam'],
      mplink: 'https://osu.ppy.sh/community/matches/58295154',
    },
    { 
      date: '08/02 - 17UTC',
      player1: 'Santeri',
      country1: '../../assets/images/flag/fi.png',
      img1: '../../assets/images/playerspfp/Santeri.png',
      player2: 'Vaf',
      country2: '../../assets/images/flag/ar.png',
      img2: '../../assets/images/playerspfp/Vaf.jpg',
      referee: 'Starger',
      streamer: 'ITotallyGetThat',
      commentators: ['Finite', 'Maou'],
      mplink: 'https://osu.ppy.sh/community/matches/58296811',
    },
    { 
      date: '08/02 - 15UTC',
      player1: 'Kozzo',
      country1: '../../assets/images/flag/it.png',
      img1: '../../assets/images/playerspfp/Kozzo.jpg',
      player2: 'Boaz',
      country2: '../../assets/images/flag/nl.png',
      img2: '../../assets/images/playerspfp/Boaz.png',
      referee: 'Brown918',
      streamer: 'ITotallyGetThat',
      commentators: ['Heam'],
      mplink: 'https://osu.ppy.sh/community/matches/58293268',
    },
    { 
      date: '08/02 - 09UTC',
      player1: 'helios44',
      country1: '../../assets/images/flag/sg.png',
      img1: '../../assets/images/playerspfp/helios44.png',
      player2: 'zd101nb',
      country2: '../../assets/images/flag/cn.png',
      img2: '../../assets/images/playerspfp/zd101nb.jpg',
      referee: 'Satsukel',
      streamer: 'E-M-i',
      commentators: ['Heam'],
      mplink: 'https://osu.ppy.sh/community/matches/58285453',
    },
    { 
      date: '08/02 - 14UTC',
      player1: 'Kirross',
      country1: '../../assets/images/flag/de.png',
      img1: '../../assets/images/playerspfp/Kirross.jpg',
      player2: 'Enohx',
      country2: '../../assets/images/flag/de.png',
      img2: '../../assets/images/playerspfp/Enohx.jpg',
      referee: 'E-M-i',
      streamer: 'ITotallyGetThat',
      commentators: ['E-M-i', 'Heam'],
      mplink: 'https://osu.ppy.sh/community/matches/58291512',
    },
    { 
      date: '09/02 - 02UTC',
      player1: 'Loliezi1337',
      country1: '../../assets/images/flag/us.png',
      img1: '../../assets/images/playerspfp/Loliezi1337.jpg',
      player2: 'Arbusion',
      country2: '../../assets/images/flag/au.png',
      img2: '../../assets/images/playerspfp/Arbusion.jpg',
      referee: 'Element118',
      streamer: 'Element118',
      commentators: ['NutAndGo'],
      mplink: 'https://osu.ppy.sh/community/matches/58310043',
    },
    { 
      date: '08/02 - 13UTC',
      player1: 'Olii',
      country1: '../../assets/images/flag/uk.jpg',
      img1: '../../assets/images/playerspfp/Olii.jpg',
      player2: 'Blujae',
      country2: '../../assets/images/flag/nz.png',
      img2: '../../assets/images/playerspfp/Blujae.jpg',
      referee: 'Element118',
      streamer: 'Element118',
      commentators: ['NutAndGo', 'Heam'],
      mplink: 'https://osu.ppy.sh/community/matches/58290286',
    },
    { 
      date: '09/02 - 18UTC',
      player1: 'BadAimBoi',
      country1: '../../assets/images/flag/pl.png',
      img1: '../../assets/images/playerspfp/BadAimBoi.jpg',
      player2: 'Yeong Yuseong',
      country2: '../../assets/images/flag/us.png',
      img2: '../../assets/images/playerspfp/Yeong Yuseong.jpg',
      referee: 'Krekker',
      streamer: 'Krekker',
      commentators: ['Finite', 'Maou'],
      mplink: 'https://osu.ppy.sh/community/matches/58328827',
    },
    { 
      date: '09/02 - 16UTC',
      player1: '-Storm7-',
      country1: '../../assets/images/flag/hk.png',
      img1: '../../assets/images/playerspfp/-Storm7-.jpg',
      player2: 'TLQ_Yoshii',
      country2: '../../assets/images/flag/fr.png',
      img2: '../../assets/images/playerspfp/TLQ_Yoshii.jpg',
      referee: 'Brown918',
      streamer: 'cheese salad',
      commentators: ['Heam'],
      mplink: 'https://osu.ppy.sh/community/matches/58325726',
    },
    { 
      date: '09/02 - 13UTC',
      player1: 'DrugManager	',
      country1: '../../assets/images/flag/de.png',
      img1: '../../assets/images/playerspfp/DrugManager.png',
      player2: 'Samoyed',
      country2: '../../assets/images/flag/fi.png',
      img2: '../../assets/images/playerspfp/Samoyed.jpg',
      referee: 'Krekker',
      streamer: 'Krekker',
      commentators: ['Finite', 'Heam'],
      mplink: 'https://osu.ppy.sh/community/matches/58320930',
    },
    { 
      date: '07/02 - 17UTC',
      player1: 'Vasyadogs',
      country1: '../../assets/images/flag/ru.png',
      img1: '../../assets/images/playerspfp/Vasyadogs.jpg',
      player2: 'moosepi',
      country2: '../../assets/images/flag/sg.png',
      img2: '../../assets/images/playerspfp/moosepi.png',
      referee: 'E-M-i',
      streamer: 'E-M-i',
      commentators: ['Vaf', 'Finite'],
      mplink: 'https://osu.ppy.sh/community/matches/58266217',
    },
    { 
      date: '09/02 - 16UTC',
      player1: 'ByTiger',
      country1: '../../assets/images/flag/de.png',
      img1: '../../assets/images/playerspfp/ByTiger.jpg',
      player2: 'Pickxarro',
      country2: '../../assets/images/flag/fi.png',
      img2: '../../assets/images/playerspfp/Pickxarro.jpg',
      referee: 'OverKurumi',
      streamer: 'E-M-i',
      commentators: ['Heam'],
      mplink: 'https://osu.ppy.sh/community/matches/58325652',
    },
    { 
      date: '07/02 - 13UTC',
      player1: 'squidstain',
      country1: '../../assets/images/flag/my.png',
      img1: '../../assets/images/playerspfp/squidstain.jpg',
      player2: 'DrDazzle',
      country2: '../../assets/images/flag/by.png',
      img2: '../../assets/images/playerspfp/DrDazzle.png',
      referee: 'Element118',
      streamer: 'Element118',
      commentators: ['Finite', 'Vaf'],
      mplink: 'https://osu.ppy.sh/community/matches/58260960',
    },
];