import { Player } from './player';

export const PLAYERS: Player[] = [
  { name: 'TLQ_Yoshii', country: '../../assets/images/flag/fr.png', seeding: 'Top Seed', taikoRank: '#10,657', ppCount: '2589', url: '' },
  { name: 'helios44', country: '../../assets/images/flag/sg.png', seeding: 'Top Seed', taikoRank: '#11,474', ppCount: '2513', url: ''  },
  { name: 'Maou', country: '../../assets/images/flag/de.png', seeding: 'Top Seed', taikoRank: '#10,215', ppCount: '10,584', url: ''  },
  { name: 'Malox', country: '../../assets/images/flag/de.png', seeding: 'Top Seed', taikoRank: '#10,058', ppCount: '10,584', url: ''  },
  { name: 'squidstain', country: '../../assets/images/flag/my.png', seeding: 'Top Seed', taikoRank: '#10,392', ppCount: '10,584', url: ''  },
  { name: 'Blujae', country: '../../assets/images/flag/nz.png', seeding: 'Top Seed', taikoRank: '#9,706', ppCount: '10,584', url: ''  },
  { name: 'Arbusion', country: '../../assets/images/flag/au.png', seeding: 'Top Seed', taikoRank: '#8,961', ppCount: '10,584', url: ''  },
  { name: 'Vasyadogs', country: '../../assets/images/flag/ru.png', seeding: 'Top Seed', taikoRank: '#11,391', ppCount: '10,584', url: ''  },
  { name: 'Vaf', country: '../../assets/images/flag/ar.png', seeding: 'Top Seed', taikoRank: '#11,079', ppCount: '10,584', url: ''  },
  { name: 'Enohx', country: '../../assets/images/flag/de.png', seeding: 'Top Seed', taikoRank: '#13,454', ppCount: '10,584', url: ''  },
  { name: 'DrugManager', country: '../../assets/images/flag/de.png', seeding: 'Top Seed', taikoRank: '#10,249', ppCount: '10,584', url: ''  },
  { name: 'Yeong Yuseong', country: '../../assets/images/flag/us.png', seeding: 'Top Seed', taikoRank: '#19,191', ppCount: '10,584', url: ''  },
  { name: 'zd101nb', country: '../../assets/images/flag/cn.png', seeding: 'Top Seed', taikoRank: '#12,107', ppCount: '10,584', url: ''  },
  { name: 'awdse22', country: '../../assets/images/flag/sg.png', seeding: 'Top Seed', taikoRank: '#9,051', ppCount: '10,584', url: ''  },
  { name: '-Storm7-', country: '../../assets/images/flag/hk.png', seeding: 'Top Seed', taikoRank: '#11,320', ppCount: '10,584', url: ''  },
  { name: 'moosepi', country: '../../assets/images/flag/sg.png', seeding: 'Top Seed', taikoRank: '#9,135', ppCount: '10,584', url: ''  },
  { name: 'NutAndGo', country: '../../assets/images/flag/nz.png', seeding: 'High Seed', taikoRank: '#17,759', ppCount: '10,584', url: ''  },
  { name: 'Dartandr', country: '../../assets/images/flag/ru.png', seeding: 'High Seed', taikoRank: '#10,080', ppCount: '10,584', url: ''  },
  { name: 'Boaz', country: '../../assets/images/flag/nl.png', seeding: 'High Seed', taikoRank: '#10,723', ppCount: '10,584', url: ''  },
  { name: 'Champs de ble', country: '../../assets/images/flag/fr.png', seeding: 'High Seed', taikoRank: '#15,279', ppCount: '10,584', url: ''  },
  { name: 'Olii', country: '../../assets/images/flag/uk.jpg', seeding: 'High Seed', taikoRank: '#10,284', ppCount: '10,584', url: ''  },
  { name: 'BadAimBoi', country: '../../assets/images/flag/pl.png', seeding: 'High Seed', taikoRank: '#14,398', ppCount: '10,584', url: ''  },
  { name: 'Katsumi', country: '../../assets/images/flag/de.png', seeding: 'High Seed', taikoRank: '#12,687', ppCount: '10,584', url: ''  },
  { name: 'Santeri', country: '../../assets/images/flag/fi.png', seeding: 'High Seed', taikoRank: '#9,055', ppCount: '10,584', url: ''  },
  { name: 'Loliezi1337', country: '../../assets/images/flag/us.png', seeding: 'High Seed', taikoRank: '#11,673', ppCount: '10,584', url: ''  },
  { name: 'yaityboi', country: '../../assets/images/flag/us.png', seeding: 'High Seed', taikoRank: '#12,945', ppCount: '10,584', url: ''  },
  { name: 'pickxarro', country: '../../assets/images/flag/fi.png', seeding: 'High Seed', taikoRank: '#13,531', ppCount: '10,584', url: ''  },
  { name: 'Kirross', country: '../../assets/images/flag/de.png', seeding: 'High Seed', taikoRank: '#10,234', ppCount: '10,584', url: ''  },
  { name: 'Megafan', country: '../../assets/images/flag/ar.png', seeding: 'High Seed', taikoRank: '#11,078', ppCount: '10,584', url: ''  },
  { name: 'Xellander', country: '../../assets/images/flag/pl.png', seeding: 'High Seed', taikoRank: '#11,047', ppCount: '10,584', url: ''  },
  { name: 'DrDazzle', country: '../../assets/images/flag/by.png', seeding: 'High Seed', taikoRank: '#13,688', ppCount: '10,584', url: ''  },
  { name: 'TorreManias', country: '../../assets/images/flag/ni.png', seeding: 'High Seed', taikoRank: '#12,383', ppCount: '10,584', url: ''  },
  { name: 'ByTiger', country: '../../assets/images/flag/de.png', seeding: 'Mid Seed', taikoRank: '#20,776', ppCount: '10,584', url: ''  },
  { name: 'Kozzo', country: '../../assets/images/flag/it.png', seeding: 'Mid Seed', taikoRank: '#12,495', ppCount: '10,584', url: ''  },
  { name: 'SergoM4444', country: '../../assets/images/flag/ru.png', seeding: 'Mid Seed', taikoRank: '#10,100', ppCount: '10,584', url: ''  },
  { name: 'Erkfir', country: '../../assets/images/flag/nz.png', seeding: 'Mid Seed', taikoRank: '#20,034', ppCount: '10,584', url: ''  },
  { name: 'poppasanas', country: '../../assets/images/flag/ru.png', seeding: 'Mid Seed', taikoRank: '#19,686', ppCount: '10,584', url: ''  },
  { name: '-jordan-', country: '../../assets/images/flag/uk.jpg', seeding: 'Mid Seed', taikoRank: '#12,014', ppCount: '10,584', url: ''  },
  { name: 'Dohland', country: '../../assets/images/flag/us.png', seeding: 'Mid Seed', taikoRank: '#28,772', ppCount: '10,584', url: ''  },
  { name: 'Pe6eHoK98', country: '../../assets/images/flag/ru.png', seeding: 'Mid Seed', taikoRank: '#15,923', ppCount: '10,584', url: ''  },
  { name: 'quadrillionaire', country: '../../assets/images/flag/us.png', seeding: 'Mid Seed', taikoRank: '#11,731', ppCount: '10,584', url: ''  },
  { name: 'SuperSquirrel51', country: '../../assets/images/flag/ca.png', seeding: 'Mid Seed', taikoRank: '#17,011', ppCount: '10,584', url: ''  },
  { name: 'Aidown', country: '../../assets/images/flag/fr.png', seeding: 'Mid Seed', taikoRank: '#27,292', ppCount: '10,584', url: ''  },
  { name: 'Hanik', country: '../../assets/images/flag/br.png', seeding: 'Mid Seed', taikoRank: '#22,163', ppCount: '10,584', url: ''  },
  { name: 'Senko-san', country: '../../assets/images/flag/ca.png', seeding: 'Mid Seed', taikoRank: '#18,410', ppCount: '10,584', url: ''  },
  { name: 'Samoyed', country: '../../assets/images/flag/fi.png', seeding: 'Mid Seed', taikoRank: '#15,699', ppCount: '10,584', url: ''  },
  { name: '0CitrineQueen0', country: '../../assets/images/flag/uk.jpg', seeding: 'Mid Seed', taikoRank: '#20,118', ppCount: '10,584', url: ''  },
  { name: 'DieButterStulle', country: '../../assets/images/flag/de.png', seeding: 'Mid Seed', taikoRank: '#17,710', ppCount: '10,584', url: ''  },
  { name: 'Ullei', country: '../../assets/images/flag/pl.png', seeding: 'Low Seed', taikoRank: '#30,576', ppCount: '10,584', url: ''  },
  { name: 'claggole', country: '../../assets/images/flag/ua.png', seeding: 'Low Seed', taikoRank: '#17,844', ppCount: '10,584', url: ''  },
  { name: 'persik23', country: '../../assets/images/flag/ru.png', seeding: 'Low Seed', taikoRank: '#22,046', ppCount: '10,584', url: ''  },
  { name: 'BitDust', country: '../../assets/images/flag/id.png', seeding: 'Low Seed', taikoRank: '#35,179', ppCount: '10,584', url: ''  },
  { name: 'HiddenDenki', country: '../../assets/images/flag/de.png', seeding: 'Low Seed', taikoRank: '#24,423', ppCount: '10,584', url: ''  },
  { name: 'Geromu Keretem', country: '../../assets/images/flag/bg.png', seeding: 'Low Seed', taikoRank: '#18,929', ppCount: '10,584', url: ''  },
  { name: 'Lazereed', country: '../../assets/images/flag/ph.png', seeding: 'Low Seed', taikoRank: '#35,971', ppCount: '10,584', url: ''  },
  { name: 'AhzekAhriman', country: '../../assets/images/flag/ru.png', seeding: 'Low Seed', taikoRank: '#20,075', ppCount: '10,584', url: ''  },
  { name: 'Ristpek', country: '../../assets/images/flag/fi.png', seeding: 'Low Seed', taikoRank: '#30,170', ppCount: '10,584', url: ''  },
  { name: 'Zidyx', country: '../../assets/images/flag/fr.png', seeding: 'Low Seed', taikoRank: '#19,555', ppCount: '10,584', url: ''  },
  { name: 'shineasone', country: '../../assets/images/flag/ca.png', seeding: 'Low Seed', taikoRank: '#22,497', ppCount: '10,584', url: ''  },
  { name: 'Fre3Styl3r', country: '../../assets/images/flag/de.png', seeding: 'Low Seed', taikoRank: '#43,049', ppCount: '10,584', url: ''  },
  { name: 'poing', country: '../../assets/images/flag/ca.png', seeding: 'Low Seed', taikoRank: '#30,512', ppCount: '10,584', url: ''  },
  { name: 'Corruptyouth', country: '../../assets/images/flag/us.png', seeding: 'Low Seed', taikoRank: '#75,205', ppCount: '10,584', url: ''  },
  { name: '-[ GuiboxFR ]-', country: '../../assets/images/flag/fr.png', seeding: 'Low Seed', taikoRank: '#94,147', ppCount: '10,584', url: ''  },
  { name: 'wawrzyn9', country: '../../assets/images/flag/pl.png', seeding: 'Low Seed', taikoRank: '#19,929', ppCount: '10,584', url: ''  },
  { name: 'Iajaygames', country: '../../assets/images/flag/uk.jpg', seeding: 'Eliminated', taikoRank: '#78,611', ppCount: '10,584', url: ''  },
  { name: '_kingi', country: '../../assets/images/flag/hk.png', seeding: 'Eliminated', taikoRank: '#13,788', ppCount: '10,584', url: ''  },
  { name: 'KeRLi_', country: '../../assets/images/flag/ru.png', seeding: 'Eliminated', taikoRank: '#77,102', ppCount: '10,584', url: ''  },
  { name: 'BeyondBoredom	', country: '../../assets/images/flag/il.png', seeding: 'Eliminated', taikoRank: '#36,956', ppCount: '10,584', url: ''  },
  { name: 'pokerfesh', country: '../../assets/images/flag/ph.png', seeding: 'Eliminated', taikoRank: '#52,773', ppCount: '10,584', url: ''  },
  { name: 'ZayyKen', country: '../../assets/images/flag/fr.png', seeding: 'Eliminated', taikoRank: '#34,556', ppCount: '10,584', url: ''  },
  { name: 'cakeboss05', country: '../../assets/images/flag/de.png', seeding: 'Eliminated', taikoRank: '#121,038', ppCount: '10,584', url: ''  },
];