import { Player } from './player';

export const PLAYERS: Player[] = [
  { name: 'TLQ_Yoshii', country: '../../assets/images/flag/france.png', seeding: 'Top Seed', taikoRank: '#10,657', ppCount: '2589' },
  { name: 'helios44', country: '../../assets/images/flag/singapour.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/poland.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/usa.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/poland.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/usa.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/poland.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/usa.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/poland.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/usa.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/poland.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/usa.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/poland.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/usa.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/poland.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/usa.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/france.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/england.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/canada.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/poland.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
  { name: 'John Doe', country: '../../assets/images/flag/usa.png', seeding: '#111', taikoRank: '#111', ppCount: '10,584' },
];

//Other countries: https://www.iconfinder.com/iconsets/set-of-vector-flag-countries