import { Player } from './player';

export const PLAYERS: Player[] = [
  { name: 'TLQ_Yoshii', country: '../../assets/images/flag/fr.png', seeding: 'Top Seed', taikoRank: '#10,680', ppCount: '2589', url: 'https://osu.ppy.sh/users/7157133/taiko' },
  { name: 'helios44', country: '../../assets/images/flag/sg.png', seeding: 'Top Seed', taikoRank: '#11,276', ppCount: '2513', url: 'https://osu.ppy.sh/users/7838361/taiko'  },
  { name: 'Maou', country: '../../assets/images/flag/de.png', seeding: 'Top Seed', taikoRank: '#10,211', ppCount: '2652', url: 'https://osu.ppy.sh/users/3867109/taiko'  },
  { name: 'Malox', country: '../../assets/images/flag/de.png', seeding: 'Top Seed', taikoRank: '#10,082', ppCount: '2668', url: 'https://osu.ppy.sh/users/4516252/taiko'  },
  { name: 'squidstain', country: '../../assets/images/flag/my.png', seeding: 'Top Seed', taikoRank: '#10,413', ppCount: '2623', url: 'https://osu.ppy.sh/users/11073207/taiko'  },
  { name: 'Blujae', country: '../../assets/images/flag/nz.png', seeding: 'Top Seed', taikoRank: '#9,735', ppCount: '2711', url: 'https://osu.ppy.sh/users/10613885/taiko'  },
  { name: 'Arbusion', country: '../../assets/images/flag/au.png', seeding: 'Top Seed', taikoRank: '#8,827', ppCount: '2838', url: 'https://osu.ppy.sh/users/11469447/taiko'  },
  { name: 'Vasyadogs', country: '../../assets/images/flag/ru.png', seeding: 'Top Seed', taikoRank: '#11,384', ppCount: '2502', url: 'https://osu.ppy.sh/users/7239762/taiko'  },
  { name: 'Vaf', country: '../../assets/images/flag/ar.png', seeding: 'Top Seed', taikoRank: '#10,785', ppCount: '2574', url: 'https://osu.ppy.sh/users/12589048'  },
  { name: 'Enohx', country: '../../assets/images/flag/de.png', seeding: 'Top Seed', taikoRank: '#13,394', ppCount: '2284', url: 'https://osu.ppy.sh/users/6375060'  },
  { name: 'DrugManager', country: '../../assets/images/flag/de.png', seeding: 'Top Seed', taikoRank: '#10,266', ppCount: '2645', url: 'https://osu.ppy.sh/users/8694649/taiko'  },
  { name: 'Yeong Yuseong', country: '../../assets/images/flag/us.png', seeding: 'Top Seed', taikoRank: '#19,236', ppCount: '1839', url: 'https://osu.ppy.sh/users/8926244/taiko'  },
  { name: 'zd101nb', country: '../../assets/images/flag/cn.png', seeding: 'Top Seed', taikoRank: '#12,128', ppCount: '2417', url: 'https://osu.ppy.sh/users/6870897'  },
  { name: 'awdse22', country: '../../assets/images/flag/sg.png', seeding: 'Top Seed', taikoRank: '#9,078', ppCount: '2799', url: 'https://osu.ppy.sh/users/8743513/taiko'  },
  { name: '-Storm7-', country: '../../assets/images/flag/hk.png', seeding: 'Top Seed', taikoRank: '#11,341', ppCount: '2508', url: 'https://osu.ppy.sh/users/12248285'  },
  { name: 'moosepi', country: '../../assets/images/flag/sg.png', seeding: 'Top Seed', taikoRank: '#9,131', ppCount: '2790', url: 'https://osu.ppy.sh/users/1868745/taiko'  },
  { name: 'NutAndGo', country: '../../assets/images/flag/nz.png', seeding: 'High Seed', taikoRank: '#17,798', ppCount: '1931', url: 'https://osu.ppy.sh/users/7740118/taiko'  },
  { name: 'Dartandr', country: '../../assets/images/flag/ru.png', seeding: 'High Seed', taikoRank: '#9,081', ppCount: '2799', url: 'https://osu.ppy.sh/users/4944211'  },
  { name: 'Boaz', country: '../../assets/images/flag/nl.png', seeding: 'High Seed', taikoRank: '#10,501', ppCount: '2611', url: 'https://osu.ppy.sh/users/13302996/'  },
  { name: 'Champs de ble', country: '../../assets/images/flag/fr.png', seeding: 'High Seed', taikoRank: '#14,799', ppCount: '2163', url: 'https://osu.ppy.sh/users/6387858'  },
  { name: 'Olii', country: '../../assets/images/flag/uk.jpg', seeding: 'High Seed', taikoRank: '#10,305', ppCount: '2639', url: 'https://osu.ppy.sh/users/7683305/taiko'  },
  { name: 'BadAimBoi', country: '../../assets/images/flag/pl.png', seeding: 'High Seed', taikoRank: '#14,436', ppCount: '2194', url: 'https://osu.ppy.sh/users/7009485/taiko'  },
  { name: 'Katsumi', country: '../../assets/images/flag/de.png', seeding: 'High Seed', taikoRank: '#12,707', ppCount: '2354', url: 'https://osu.ppy.sh/users/513834'  },
  { name: 'Santeri', country: '../../assets/images/flag/fi.png', seeding: 'High Seed', taikoRank: '#8,711', ppCount: '2855', url: 'https://osu.ppy.sh/users/1981187/taiko'  },
  { name: 'Loliezi1337', country: '../../assets/images/flag/us.png', seeding: 'High Seed', taikoRank: '#11,671', ppCount: '2469', url: 'https://osu.ppy.sh/users/12990096/taiko'  },
  { name: 'yaityboi', country: '../../assets/images/flag/us.png', seeding: 'High Seed', taikoRank: '#12,975', ppCount: '2326', url: 'https://osu.ppy.sh/users/2194368/taiko'  },
  { name: 'pickxarro', country: '../../assets/images/flag/fi.png', seeding: 'High Seed', taikoRank: '#13,207', ppCount: '2305', url: 'https://osu.ppy.sh/users/3786620/taiko'  },
  { name: 'Kirross', country: '../../assets/images/flag/de.png', seeding: 'High Seed', taikoRank: '#10,238', ppCount: '2650', url: 'https://osu.ppy.sh/users/10893243'  },
  { name: 'Megafan', country: '../../assets/images/flag/ar.png', seeding: 'High Seed', taikoRank: '#11,085', ppCount: '2538', url: 'https://osu.ppy.sh/users/6632605/taiko'  },
  { name: 'Xellander', country: '../../assets/images/flag/pl.png', seeding: 'High Seed', taikoRank: '#11,072', ppCount: '2539', url: 'https://osu.ppy.sh/users/6573608/taiko'  },
  { name: 'DrDazzle', country: '../../assets/images/flag/by.png', seeding: 'High Seed', taikoRank: '#13,731', ppCount: '2256', url: 'https://osu.ppy.sh/users/6216290'  },
  { name: 'TorreManias', country: '../../assets/images/flag/ni.png', seeding: 'High Seed', taikoRank: '#12,404', ppCount: '2387', url: 'https://osu.ppy.sh/users/13181637'  },
  { name: 'ByTiger', country: '../../assets/images/flag/de.png', seeding: 'Mid Seed', taikoRank: '#18,965', ppCount: '1854', url: 'https://osu.ppy.sh/users/10242297/taiko'  },
  { name: 'Kozzo', country: '../../assets/images/flag/it.png', seeding: 'Mid Seed', taikoRank: '#12,447', ppCount: '2382', url: 'https://osu.ppy.sh/users/11993912'  },
  { name: 'SergoM4444', country: '../../assets/images/flag/ru.png', seeding: 'Mid Seed', taikoRank: '#9,425', ppCount: '2750', url: 'https://osu.ppy.sh/users/10515166/taiko'  },
  { name: 'Erkfir', country: '../../assets/images/flag/nz.png', seeding: 'Mid Seed', taikoRank: '#20,096', ppCount: '1791', url: 'https://osu.ppy.sh/users/7756939/taiko'  },
  { name: 'poppasanas', country: '../../assets/images/flag/ru.png', seeding: 'Mid Seed', taikoRank: '#19,727', ppCount: '1812', url: 'https://osu.ppy.sh/users/8717773/taiko'  },
  { name: '-jordan-', country: '../../assets/images/flag/uk.jpg', seeding: 'Mid Seed', taikoRank: '#12,017', ppCount: '2429', url: 'https://osu.ppy.sh/users/7288862/taiko'  },
  { name: 'Dohland', country: '../../assets/images/flag/us.png', seeding: 'Mid Seed', taikoRank: '#28,848', ppCount: '1418', url: 'https://osu.ppy.sh/users/5220511/taiko'  },
  { name: 'Pe6eHoK98', country: '../../assets/images/flag/ru.png', seeding: 'Mid Seed', taikoRank: '#15,943', ppCount: '2070', url: 'https://osu.ppy.sh/users/15575520/taiko'  },
  { name: 'quadrillionaire', country: '../../assets/images/flag/us.png', seeding: 'Mid Seed', taikoRank: '#11,759', ppCount: '2459', url: 'https://osu.ppy.sh/users/15139170'  },
  { name: 'SuperSquirrel51', country: '../../assets/images/flag/ca.png', seeding: 'Mid Seed', taikoRank: '#17,049', ppCount: '1985', url: 'https://osu.ppy.sh/users/6468829/taiko'  },
  { name: 'Aidown', country: '../../assets/images/flag/fr.png', seeding: 'Mid Seed', taikoRank: '#27,361', ppCount: '1469', url: 'https://osu.ppy.sh/users/1522146/taiko'  },
  { name: 'Hanik', country: '../../assets/images/flag/br.png', seeding: 'Mid Seed', taikoRank: '#22,215', ppCount: '1682', url: 'https://osu.ppy.sh/users/4533507/taiko'  },
  { name: 'Senko-san', country: '../../assets/images/flag/ca.png', seeding: 'Mid Seed', taikoRank: '#18,029', ppCount: '1914', url: 'https://osu.ppy.sh/users/2065771/taiko'  },
  { name: 'Samoyed', country: '../../assets/images/flag/fi.png', seeding: 'Mid Seed', taikoRank: '#15,739', ppCount: '2086', url: 'https://osu.ppy.sh/users/6796557/taiko'  },
  { name: '0CitrineQueen0', country: '../../assets/images/flag/uk.jpg', seeding: 'Mid Seed', taikoRank: '#20,179', ppCount: '1787', url: 'https://osu.ppy.sh/users/15285061'  },
  { name: 'DieButterStulle', country: '../../assets/images/flag/de.png', seeding: 'Mid Seed', taikoRank: '#17,461', ppCount: '1955', url: 'https://osu.ppy.sh/users/4965323/taiko'  },
  { name: 'Ullei', country: '../../assets/images/flag/pl.png', seeding: 'Low Seed', taikoRank: '#30,658', ppCount: '1363', url: 'https://osu.ppy.sh/users/8124223/taiko'  },
  { name: 'claggole', country: '../../assets/images/flag/ua.png', seeding: 'Low Seed', taikoRank: '#17,497', ppCount: '1953', url: 'https://osu.ppy.sh/users/2251001/taiko'  },
  { name: 'persik23', country: '../../assets/images/flag/ru.png', seeding: 'Low Seed', taikoRank: '#21,859', ppCount: '1699', url: 'https://osu.ppy.sh/users/15278988/taiko'  },
  { name: 'BitDust', country: '../../assets/images/flag/id.png', seeding: 'Low Seed', taikoRank: '#35,284', ppCount: '1236', url: 'https://osu.ppy.sh/users/9573836/taiko'  },
  { name: 'HiddenDenki', country: '../../assets/images/flag/de.png', seeding: 'Low Seed', taikoRank: '#24,481', ppCount: '1580', url: 'https://osu.ppy.sh/users/6868059'  },
  { name: 'Geromu Keretem', country: '../../assets/images/flag/bg.png', seeding: 'Low Seed', taikoRank: '#18,851', ppCount: '1861', url: 'https://osu.ppy.sh/users/9404532/taiko'  },
  { name: 'Lazereed', country: '../../assets/images/flag/ph.png', seeding: 'Low Seed', taikoRank: '#36,074', ppCount: '1216', url: 'https://osu.ppy.sh/users/12894120/taiko'  },
  { name: 'AhzekAhriman', country: '../../assets/images/flag/ru.png', seeding: 'Low Seed', taikoRank: '#19,428', ppCount: '1828', url: 'https://osu.ppy.sh/users/11705785/taiko'  },
  { name: 'Ristpek', country: '../../assets/images/flag/fi.png', seeding: 'Low Seed', taikoRank: '#30,254', ppCount: '1375', url: 'https://osu.ppy.sh/users/11819476'  },
  { name: 'Zidyx', country: '../../assets/images/flag/fr.png', seeding: 'Low Seed', taikoRank: '#19,533', ppCount: '1822', url: 'https://osu.ppy.sh/users/3859586/taiko'  },
  { name: 'shineasone', country: '../../assets/images/flag/ca.png', seeding: 'Low Seed', taikoRank: '#22,545', ppCount: '1666', url: 'https://osu.ppy.sh/users/6203507/taiko'  },
  { name: 'Fre3Styl3r', country: '../../assets/images/flag/de.png', seeding: 'Low Seed', taikoRank: '#43,138', ppCount: '1063', url: 'https://osu.ppy.sh/users/10177249/taiko'  },
  { name: 'poing', country: '../../assets/images/flag/ca.png', seeding: 'Low Seed', taikoRank: '#30,594', ppCount: '1365', url: 'https://osu.ppy.sh/users/3330914/taiko'  },
  { name: 'Corruptyouth', country: '../../assets/images/flag/us.png', seeding: 'Low Seed', taikoRank: '#75,418', ppCount: '630', url: 'https://osu.ppy.sh/users/10229945/taiko'  },
  { name: '-[ GuiboxFR ]-', country: '../../assets/images/flag/fr.png', seeding: 'Low Seed', taikoRank: '#94,403', ppCount: '487', url: 'https://osu.ppy.sh/users/11261739/taiko'  },
  { name: 'wawrzyn9', country: '../../assets/images/flag/pl.png', seeding: 'Low Seed', taikoRank: '#19,058', ppCount: '1849', url: 'https://osu.ppy.sh/users/11181328'  },
  { name: 'Iajaygames', country: '../../assets/images/flag/uk.jpg', seeding: 'Eliminated', taikoRank: '#78,757', ppCount: '601', url: 'https://osu.ppy.sh/users/10080805/taiko'  },
  { name: '_kingi', country: '../../assets/images/flag/hk.png', seeding: 'Eliminated', taikoRank: '#13,896', ppCount: '2241', url: 'https://osu.ppy.sh/users/3339073/taiko'  },
  { name: 'KeRLi_', country: '../../assets/images/flag/ru.png', seeding: 'Eliminated', taikoRank: '#77,795', ppCount: '609', url: 'https://osu.ppy.sh/users/5902629/taiko'  },
  { name: 'BeyondBoredom	', country: '../../assets/images/flag/il.png', seeding: 'Eliminated', taikoRank: '#37,271', ppCount: '1187', url: 'https://osu.ppy.sh/users/11094269/taiko'  },
  { name: 'pokerfesh', country: '../../assets/images/flag/ph.png', seeding: 'Eliminated', taikoRank: '#53,218', ppCount: '892', url: 'https://osu.ppy.sh/users/14351977/taiko'  },
  { name: 'ZayyKen', country: '../../assets/images/flag/fr.png', seeding: 'Eliminated', taikoRank: '#34,842', ppCount: '1246', url: 'https://osu.ppy.sh/users/8624433/taiko'  },
  { name: 'cakeboss05', country: '../../assets/images/flag/de.png', seeding: 'Eliminated', taikoRank: '#122,151', ppCount: '350', url: 'https://osu.ppy.sh/users/12586864/taiko'  },
];